# proj3.gocd.yaml
pipelines:
  build:
    group: monoproj3
    materials:
      mygit:
        git: https://github.com/njdnet101/monotest
        whitelist:
          - proj3/**/*
        shallow_clone: true
    stages:
      - build:
          jobs:
            build:
              tasks:
                - exec: # indicates type of task
                    command: ./build
                    working_directory: proj3
      - integrationTest:
          jobs:
            integrationTest:
              tasks:
                - exec:
                    command: pwd
            uiTest:
              tasks:
                - exec:
                    command: pwd
  performance:
    group: monoproj3
    materials:
      mydependency:
        pipeline: build
        stage: integrationTest
      mygit:
        git: https://github.com/njdnet101/monotest
        whitelist:
          - proj3/**/*
    stages:
      - deploy:
          jobs:
            deploy:
              tasks:
                - exec: # indicates type of task
                    command: pwd
      - performanceTest:
          jobs:
            performanceTest:
              tasks:
                - exec: # indicates type of task
                    command: pwd
