#!/bin/bash

echo "post command before"

echo "$BUILDKITE_PIPELINE_SLUG"
echo "$BUILDKITE_CHECKOUT_PATH"

case "$BUILDKITE_PIPELINE_SLUG" in
proj1)
  export BUILDKITE_CHECKOUT_PATH="$BUILDKITE_CHECKOUT_PATH/proj1"
  ;;
proj2)
  export BUILDKITE_CHECKOUT_PATH="$BUILDKITE_CHECKOUT_PATH/proj2"
  ;;
*)
  # Leave the path alone and run the main pipeline
esac

echo "post command after"

echo "$BUILDKITE_PIPELINE_SLUG"
echo "$BUILDKITE_CHECKOUT_PATH"
